# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RSS-Feed
version:      2
version_from: lib/XML/RSS/Feed.pm
installdirs:  site
requires:
    Clone:                         0
    Digest::MD5:                   0
    Encode:                        0
    HTML::Entities:                0
    Storable:                      0
    Time::HiRes:                   0
    URI:                           0
    XML::RSS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
