--- #YAML:1.0
name:                XML-RSS-Feed
version:             2.3
abstract:            Persistant XML RSS Encapsulation
license:             perl
author:              
    - Jeff Bisbee <jbisbee@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    Clone:                         0
    Digest::MD5:                   0
    Encode:                        0
    HTML::Entities:                0
    Storable:                      0
    Test::More:                    0
    Time::HiRes:                   0
    URI:                           0
    XML::RSS:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
