# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RSS-Feed
version:      0.2
version_from: lib/XML/RSS/Feed.pm
installdirs:  site
requires:
    XML::RSS:                      0.97

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
